// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:3696e01c-da3a-47ed-969b-053f95df941e",
    "aws_cognito_region": "ap-northeast-1",
    "aws_mobile_analytics_app_id": "530adfeedef0484da6f87e0caf17f881",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
